# Generated by Django 4.1.5 on 2023-01-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'room_id')},
        ),
    ]
